name: Test

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: LUDEX_CLIENT_API_KEY=${{ secrets.COINFLIP_CLIENT_API_KEY }} LUDEX_ORG_API_KEY=${{ secrets.LUDEX_ORG_API_KEY }} cargo test
